// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyoomwlvtenatbhtniic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5b29td2x2dGVuYXRiaHRuaWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMTcwODMsImV4cCI6MjA1NDY5MzA4M30.LwHc-Kjkz_maiq3FiX6oKhw-wWW7fe4R687cXNI_2_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);